[package]
name = "test_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.3"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
sha3 = "0.10.8"
hex-literal = "0.4.1"
hex = "0.4.3"